#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a android-studio state=floating border=off follow=on

wmname LG3D &

picom &
dunst &
feh --bg-scale $HOME/Pictures/girl.jpg &
xset led 3 &
~/.config/polybar/launch.sh &
/usr/lib/kdeconnectd &
easystroke &
lxpolkit &
redshift &
numlockx &
